version: '3.8'

services:
  whats_agent:
    image: whats_agent:latest
    networks:
      - whats_agent
    secrets:
      - database_password
      - openai_api_key
      - meta_access_token
      - webhook_verify_token
      - jwt_secret
    environment:
      - ENVIRONMENT=production
      - USE_DOCKER_SECRETS=true
    volumes:
      - ./logs:/app/logs
    ports:
      - "8000:8000"

secrets:
  database_password:
    external: true
  openai_api_key:
    external: true
  meta_access_token:
    external: true
  webhook_verify_token:
    external: true
  jwt_secret:
    external: true

networks:
  whats_agent:
    external: true
