global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: 'whatsapp-agent'
    static_configs:
      - targets: ['wppagent-production.up.railway.app']
    metrics_path: '/metrics'
    scheme: 'https'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s
