"""update_bot_configuration_fields

Revision ID: 2566fe4639c3
Revises: bb3644832d05
Create Date: 2025-07-29 23:53:41.725550-03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2566fe4639c3'
down_revision = 'bb3644832d05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_configurations', sa.Column('auto_response_enabled', sa.Boolean(), nullable=True))
    op.add_column('bot_configurations', sa.Column('response_delay_min', sa.Integer(), nullable=True))
    op.add_column('bot_configurations', sa.Column('response_delay_max', sa.Integer(), nullable=True))
    op.add_column('bot_configurations', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('bot_configurations', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('bot_configurations', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('bot_configurations', sa.Column('max_message_length', sa.Integer(), nullable=True))
    op.add_column('bot_configurations', sa.Column('working_hours_only', sa.Boolean(), nullable=True))
    op.add_column('bot_configurations', sa.Column('weekend_support', sa.Boolean(), nullable=True))
    op.add_column('bot_configurations', sa.Column('appointment_enabled', sa.Boolean(), nullable=True))
    op.add_column('bot_configurations', sa.Column('max_appointments_per_day', sa.Integer(), nullable=True))
    op.add_column('bot_configurations', sa.Column('appointment_buffer_minutes', sa.Integer(), nullable=True))
    op.add_column('bot_configurations', sa.Column('notification_lead_time_hours', sa.Integer(), nullable=True))
    op.add_column('bot_configurations', sa.Column('follow_up_enabled', sa.Boolean(), nullable=True))
    op.add_column('bot_configurations', sa.Column('follow_up_delay_minutes', sa.Integer(), nullable=True))
    op.add_column('bot_configurations', sa.Column('data_collection_enabled', sa.Boolean(), nullable=True))
    op.add_column('bot_configurations', sa.Column('required_fields', sa.JSON(), nullable=True))
    op.add_column('bot_configurations', sa.Column('optional_fields', sa.JSON(), nullable=True))
    op.drop_column('bot_configurations', 'require_phone_confirmation')
    op.drop_column('bot_configurations', 'require_full_name')
    op.drop_column('bot_configurations', 'require_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_configurations', sa.Column('require_email', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('bot_configurations', sa.Column('require_full_name', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('bot_configurations', sa.Column('require_phone_confirmation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('bot_configurations', 'optional_fields')
    op.drop_column('bot_configurations', 'required_fields')
    op.drop_column('bot_configurations', 'data_collection_enabled')
    op.drop_column('bot_configurations', 'follow_up_delay_minutes')
    op.drop_column('bot_configurations', 'follow_up_enabled')
    op.drop_column('bot_configurations', 'notification_lead_time_hours')
    op.drop_column('bot_configurations', 'appointment_buffer_minutes')
    op.drop_column('bot_configurations', 'max_appointments_per_day')
    op.drop_column('bot_configurations', 'appointment_enabled')
    op.drop_column('bot_configurations', 'weekend_support')
    op.drop_column('bot_configurations', 'working_hours_only')
    op.drop_column('bot_configurations', 'max_message_length')
    op.drop_column('bot_configurations', 'timezone')
    op.drop_column('bot_configurations', 'language')
    op.drop_column('bot_configurations', 'max_retries')
    op.drop_column('bot_configurations', 'response_delay_max')
    op.drop_column('bot_configurations', 'response_delay_min')
    op.drop_column('bot_configurations', 'auto_response_enabled')
    # ### end Alembic commands ###
