groups:
  - name: whatsapp_agent_alerts
    rules:
      # API Down
      - alert: WhatsAppAgentDown
        expr: up{job="whatsapp-agent"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "WhatsApp Agent API is down"
          description: "WhatsApp Agent has been down for more than 1 minute"

      # High Response Time
      - alert: HighResponseTime
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "Response time is above 1 second for 2 minutes"

      # High Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate"
          description: "Error rate is above 10% for 5 minutes"

      # Rate Limit Hits
      - alert: RateLimitHits
        expr: rate(rate_limit_hits_total[5m]) > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High rate limit hits"
          description: "Rate limiting is being triggered frequently (>10/5min)"

      # Database Connection Issues
      - alert: DatabaseConnectionFailed
        expr: database_connections_failed_total > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Database connection failed"
          description: "Failed to connect to PostgreSQL database"

      # Memory Usage High
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / 1024 / 1024 > 500
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 500MB for 10 minutes"

      # Webhook Processing Slow
      - alert: WebhookProcessingSlow
        expr: rate(webhook_processing_duration_seconds_sum[5m]) / rate(webhook_processing_duration_seconds_count[5m]) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Webhook processing is slow"
          description: "Webhook processing time is above 2 seconds for 5 minutes"

      # No webhook messages received
      - alert: NoWebhookMessages
        expr: rate(webhook_messages_processed_total[10m]) == 0
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "No webhook messages received"
          description: "No webhook messages processed in the last 30 minutes"

      # Lead scoring failures
      - alert: LeadScoringFailures
        expr: rate(lead_scoring_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Lead scoring failures detected"
          description: "Lead scoring error rate is above 10%"

      # Cache hit rate low
      - alert: LowCacheHitRate
        expr: cache_hit_rate < 0.7
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is below 70% for 10 minutes"
